### ISSUE TITLE
3.0.14 Error: ERR wrong number of arguments for 'set' command (Redis::CommandError)

### ISSUE THREAD

**Issue by QuintinAdam** [mhenrixon/sidekiq-unique-jobs#104]
After upgrading to 3.0.14 I receive this error for any of my jobs using unique jobs.

Probably coming from https://github.com/mhenrixon/sidekiq-unique-jobs/blob/057b606b1ec5b0872d67be0af9e7578dbc035af3/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb#L51

ruby '2.2.2'

rails (4.1.12)
sidekiq (3.4.2)
sidekiq-unique-jobs (3.0.14)
redis (3.2.1)

Stack trace
```
E, [2015-08-17T13:54:54.375675 #22540] ERROR -- : ERR wrong number of arguments for 'set' command (Redis::CommandError)
/home/api/application/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
/home/api/application/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:679:in `block in set'
/home/api/application/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
/home/api/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/api/application/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
/home/api/application/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis.rb:677:in `set'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb:78:in `block in new_unique_for?'
/home/api/application/shared/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/home/api/application/shared/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/home/api/application/shared/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/home/api/application/shared/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/home/api/application/shared/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/connectors/redis_pool.rb:6:in `connection'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/connectors.rb:11:in `block in connection'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/connectors.rb:10:in `each'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/connectors.rb:10:in `connection'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb:91:in `connection'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb:77:in `new_unique_for?'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb:50:in `unique_for_connection?'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb:37:in `review'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/strategies/unique.rb:20:in `review'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-3.0.14/lib/sidekiq_unique_jobs/middleware/client/unique_jobs.rb:21:in `call'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/client.rb:207:in `process_single'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/client.rb:65:in `push'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/worker.rb:86:in `client_push'
/home/api/application/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/worker.rb:55:in `perform_in'
...
```

Let me know if I can provide any more information or help out.

**Comment by mhenrixon** [comment]
Your redis is old, see the readme about that. Is a configuration option to turn back the old way of unique checking.

**Comment by QuintinAdam** [comment]
Thanks for the quick reply! Fixed it.
