### ISSUE TITLE
Gem requires Redis 2.6+?

### ISSUE THREAD

**Issue by andrewjwu** [mhenrixon/sidekiq-unique-jobs#109]
I'm running Redis 2.4.x and get the following error when trying to enqueue a job:

```
Redis::CommandError - ERR unknown command 'eval'
```

The README seems to imply that Redis < 2.6.x is supported by setting:

```ruby
SidekiqUniqueJobs.config.unique_storage_method = :old
```

but this doesn't seem to fix it. Seems like 2.6.x is a hard requirement, can you confirm?

**Comment by mhenrixon** [comment]
Stack trace?

**Comment by andrewjwu** [comment]
```
Redis::CommandError - ERR unknown command 'eval':
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:2277:in `block in _eval'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
  /usr/lib64/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:2276:in `_eval'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-3.2.1/lib/redis.rb:2303:in `eval'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:283:in `eval'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-unique-jobs-3.0.15/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:57:in `block in unlock'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq.rb:70:in `redis'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-unique-jobs-3.0.15/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:56:in `unlock'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-unique-jobs-3.0.15/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:19:in `delete_ext'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/web.rb:234:in `retry_or_delete'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/web.rb:145:in `block (2 levels) in <class:Web>'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/web.rb:143:in `each'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/web.rb:143:in `block in <class:Web>'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `block in compile!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-protection-1.5.2/lib/rack/protection/xss_header.rb:18:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-protection-1.5.2/lib/rack/protection/path_traversal.rb:16:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-protection-1.5.2/lib/rack/protection/json_csrf.rb:18:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-protection-1.5.2/lib/rack/protection/base.rb:50:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-protection-1.5.2/lib/rack/protection/frame_options.rb:31:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/nulllogger.rb:9:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/head.rb:9:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/mapper.rb:43:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/dragonfly-1.0.10/lib/dragonfly/middleware.rb:14:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/pdfkit-0.6.2/lib/pdfkit/middleware.rb:17:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/versionist-1.4.1/lib/versionist/middleware.rb:39:in `_call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/versionist-1.4.1/lib/versionist/middleware.rb:17:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__2588998102669128060__call__3679078114763141854__callbacks'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/sendfile.rb:102:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rollbar-1.5.3/lib/rollbar.rb:799:in `scoped'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rollbar-1.5.3/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/dragonfly-1.0.10/lib/dragonfly/cookie_monster.rb:9:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'
  /data/MyApp/shared/bundled_gems/ruby/2.0.0/gems/unicorn-4.8.2/bin/unicorn:126:in `<top (required)>'
  /data/MyApp/current/ey_bundler_binstubs/unicorn:16:in `load'
  /data/MyApp/current/ey_bundler_binstubs/unicorn:16:in `<main>
```

**Comment by mhenrixon** [comment]
Slight oversight by me, I'll get a fix in tomorrow.

**Comment by andrewjwu** [comment]
Thanks!

**Comment by mhenrixon** [comment]
Redis 2.6.2 required
