### ISSUE TITLE
ActiveRecord::RecordNotDestroyed: Failed to destroy the record

### ISSUE THREAD

**Issue by benoittgt** [mhenrixon/sidekiq-unique-jobs#139]
Hello

We are using Sidekiq unique jobs but we have an issue when we want to destroy resources.

```ruby
  def destroy
    old_store = mobile_application.store
    users_ids = [1,2]
    super

    UpdateLastUpdatesWorker.perform_async old_store.id, users_ids
    mobile_application.last_update = mobile_application.old_last_update
    mobile_application.save!
  end
```
Tests pass (but wrong code)

```ruby
  def destroy
    old_store = mobile_application.store
    super

    UpdateLastUpdatesWorker.perform_async old_store.id
    mobile_application.last_update = mobile_application.old_last_update
    mobile_application.save!
  end
```
Tests fails with "Failed to destroy the record"

If we edit the worker line with :

```ruby
UpdateLastUpdatesWorker.perform_async old_store.id
```
fail !

```ruby
UpdateLastUpdatesWorker.perform_async old_store.id, []
```
Tests pass !

When enable logging I have this : 
```
2015-10-22T15:51:26.145Z 61863 TID-oxfq6a7ek WARN: payload is not unique {"class"=>"UpdateLastUpdatesWorker", "args"=>[57223], "retry"=>true, "queue"=>"visibility", "unique"=>:until_and_while_executing, "log_duplicate_payload"=>true, "jid"=>"bc6fd6988a40d96fef815f09", "created_at"=>1445529086.144471, "unique_prefix"=>"uniquejobs", "unique_args"=>[57223], "unique_digest"=>"uniquejobs:5e0cd05429e02379f0e8193e4bd9430c »}
```

**Comment by mhenrixon** [comment]
You will have to investigate your setup. Have a hard time picturing that has to do with unique jobs gem. Wild guess, you have test_after_commit installed.

**Comment by mhenrixon** [comment]
Also can't see how you configured your worker. Bet your unique args configuration isn't working could be related to #138

**Comment by mhenrixon** [comment]
What testing mode is configured for sidekiq?

**Comment by benoittgt** [comment]
Test is a unit test

```ruby
  test 'destroy should cascade mobile applications' do
    store_2 = create_store :organisation => @organisation
    store_2.add_as_admin @admin

    create_mobile_application :store => @store, :mobile_application_update => {:binary_file_name => nil}

    assert_difference ['MobileApplication.count', 'MobileApplicationUpdate.count', 'Store.count'], -1 do
      @store.destroy
    end
  end
```

and the worker looks like this

```ruby
class UpdateLastUpdatesWorker
  include Sidekiq::Worker
  sidekiq_options queue: :visibility, unique: :until_and_while_executing

  def perform(store_id, users_ids=nil)
    ....
  end
end
```

**Comment by mhenrixon** [comment]
Thanks for the test case, I'll investigate it!

**Comment by mhenrixon** [comment]
This is a lot to ask I know but could you put together a sample rails application that replicates this problem using a subset of the application you are working on? I really want to get to the bottom of this but I don’t want to spend unnecessary time failing to replicate the problem. 

Does the test fail when only that test is run as well or does it only fail when the whole suite is run? If the test always fail you could do something like this in a before block:

```ruby
before do 
  Sidekiq.logger.level = Logger::DEBUG
end
```

That should give you some very detailed output from `SidekiqUniqueJobs::UniqueArgs` class that would be helpful.

It would also be helpful to know what sidekiq test mode you are running in for the given test eg.

```ruby
config.before(:each) do |example|
  Sidekiq::Testing.disable! # this causes unique jobs to behave slightly different for .fake!, .inline! and .disable!
end
```

**Comment by benoittgt** [comment]
Thanks Mikael

We will investigate and publish the log and the sidekiq test mode. We add a ticket in our backlog for our next spring.

For the moment we have this

```ruby
 def destroy
    super
    mobile_application.last_update = mobile_application.old_last_update
    mobile_application.save!
    GroupUtility.delay.update_last_updates mobile_application.store_id
  end
```

Thanks a lot for your help.

**Comment by mhenrixon** [comment]
I'm closing this until you can get me all the details. Get back to me with an example application where you have replicated this problem in an isolated environment. Just like in #142 and I'll be able to help you!

**Comment by benoittgt** [comment]
Thanks Mikael.

**Comment by benoittgt** [comment]
Hello @mhenrixon 
I'm working again on this issue.

When I'm deleting a store
```ruby
#spec/models/store_spec.rb
  describe '#destroy' do
    let!(:group) { create :group, store: store }
    let!(:group2) { create :group, store: store }

    Sidekiq::Testing.inline! do

      it 'destroy store' do
        expect{ store.destroy }.to change { Store.count }.by(-1)
      end

      it 'destroy related groups' do
        expect{ store.destroy }.to change { Group.count }.by(-3)
      end
    end
  end

#Failure/Error: store.destroy
#  1) Store#destroy destroy store
#     Failure/Error: expect{ store.destroy }.to change { Store.count }.by(-1)
#     ActiveRecord::RecordNotDestroyed:
#       Failed to destroy the record
#  2) Store#destroy destroy related groups
#     Failure/Error: expect{ store.destroy }.to change { Group.count }.by(-3)
#     ActiveRecord::RecordNotDestroyed:
#       Failed to destroy the record
```

My destroy methods have few methods : 
```ruby
#app/models/store.rb
  def destroy
    users_to_delete = users_only_related_to_this_store
    Category.where(store_id: self.id).destroy_all
    super
    users_to_delete.destroy_all
  end
```
And because store have many group with a dependent destroy. Group need to be destroy that where the problem happen. 

```
#app/models/group.rb
  def destroy
    old_store = store
    super
    UpdateLastUpdatesWorker.perform_async old_store.id
  end
```

The destroy action is made one time. I've added a `puts "\n worker is #{worker}, job #{job['args']}"
` in [gem code](https://github.com/mhenrixon/sidekiq-unique-jobs/blob/master/lib/sidekiq_unique_jobs/testing/sidekiq_overrides.rb#L26). It returns ` worker is #<UpdateLastUpdatesWorker:0x007fb7d5009828>, job [50823]`, I see that it get into the worker, then try to call again `Group#destroy` for the next group. Then it breaks.

Worker looks like this.

```ruby
class UpdateLastUpdatesWorker
  include Sidekiq::Worker
  sidekiq_options queue: :visibility, unique: :until_and_while_executing

  def perform(store_id)
    GroupUtility.update_last_updates(store_id)
  end
end
```
If I comment `unique` option
```ruby
  sidekiq_options queue: :visibility#, unique: :until_and_while_executing
```

Then all test are green. It seems that `unique: :until_and_while_executing` have a callback that block the destroy action. 

Don't know if it's enough to get feedbacks from you. I will keep digging.

**Comment by benoittgt** [comment]
Full stack trace

```
     Failure/Error: expect{ store.destroy }.to change { Group.count }.by(-3)
     ActiveRecord::RecordNotDestroyed:
       Failed to destroy the record
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/persistence.rb:185:in `destroy!'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/has_many_association.rb:166:in `each'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/has_many_association.rb:166:in `delete_records'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:531:in `remove_records'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:524:in `block in delete_or_destroy'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:182:in `transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:524:in `delete_or_destroy'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:279:in `destroy'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:223:in `destroy_all'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/has_many_association.rb:27:in `handle_dependency'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:146:in `block in add_destroy_callbacks'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:446:in `instance_exec'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:446:in `block in make_lambda'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:162:in `call'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:162:in `block in halting'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `block in call'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `each'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/callbacks.rb:292:in `destroy'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/transactions.rb:281:in `block in destroy'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activerecord-4.2.3/lib/active_record/transactions.rb:281:in `destroy'
     # ./app/models/store.rb:587:in `destroy'
     # ./spec/models/store_spec.rb:1104:in `block (5 levels) in <top (required)>'
     # ./spec/models/store_spec.rb:1104:in `block (4 levels) in <top (required)>'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
     # /Users/bti/.rvm/gems/ruby-2.2.2@appaloosa/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
```

**Comment by benoittgt** [comment]
With a worker like this : 

```ruby
class UpdateLastUpdatesWorker
  include Sidekiq::Worker
  sidekiq_options queue: :visibility, log_duplicate_payload: true, unique: :until_and_while_executing

  def perform(store_id)
    puts "from UpdateLastUpdatesForUserWorker #{store_id}"
  end
end
```

It still failling and I get this warning:

```
2015-12-17T09:55:30.404Z 15745 TID-ovnj8q5fo WARN: payload is not unique {"class"=>"UpdateLastUpdatesWorker", "args"=>[50928], "retry"=>true, "queue"=>"visibility", "log_duplicate_payload"=>true, "unique"=>:until_and_while_executing, "jid"=>"c7f9d8ea291be9f0d500aa39", "created_at"=>1450346130.404194, "unique_prefix"=>"uniquejobs", "unique_args"=>[50928], "unique_digest"=>"uniquejobs:374b917276a14ef8c5c75d25e0f4f8ad"}
2015-12-17T09:55:30.487Z 15745 TID-ovnj8q5fo WARN: payload is not unique {"class"=>"UpdateLastUpdatesWorker", "args"=>[50929], "retry"=>true, "queue"=>"visibility", "log_duplicate_payload"=>true, "unique"=>:until_and_while_executing, "jid"=>"55122ec9ca6905d4f535d49a", "created_at"=>1450346130.487124, "unique_prefix"=>"uniquejobs", "unique_args"=>[50929], "unique_digest"=>"uniquejobs:f76c5d66cbd66e6d9db7bb59e9c9ca30"}
```

**Comment by mhenrixon** [comment]
If any of those destroy returns nil or false it will all be rolled back. I suggest you rename your destroy overrides and call them something else. You will have a really hard time getting to grips with code that is written in this way.

I fear this has nothing to do with unique jobs. I recommend you look into https://github.com/makandra/active_type or refactor towards a service object.

Why are you using inline testing? If the background job returns false or nil for whatever reason your entire sequence will fail.

**Comment by benoittgt** [comment]
Thanks a lot @mhenrixon for your fast answer. It helps me a lot.

I move my worker call to and `after_destroy` so it's separate and it's work for now in test. Have to test in real conditions.

Didn't know [active_type](https://github.com/makandra/active_type) thanks for this tips.

For the inline testing. I wanted to run the full sequence with the job executed. 

Thanks again !

**Comment by mhenrixon** [comment]
You are most welcome! Glad I could offer some direction. I'd be happy to talk more about your code and how you might improve it if you want. Don't hesitate to get in contact if you need it. Speaking of active_type they wrote a book about how they use it to build rails applications. I found their approach very nice in terms of extending rails models towards one class per single purpose.

**Comment by benoittgt** [comment]
Thanks a lot @mhenrixon for your proposition. I definitely gonna have a look to [the book](https://leanpub.com/growing-rails).
