### ISSUE TITLE
Seeing this error with latest version 4.0.12

### ISSUE THREAD

**Issue by kapso** [mhenrixon/sidekiq-unique-jobs#154]
Seeing this error. This is with `sidekiq-4.0.1`

Its a standard worker with following options

```
sidekiq_options queue: :notify,
                  unique: :until_executed
```

```undefined method `to_sym' for true:TrueClass```

```ruby
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.12/lib/sidekiq_unique_jobs/options_with_fallback.rb:25:in `lock_class'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.12/lib/sidekiq_unique_jobs/options_with_fallback.rb:21:in `lock'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.12/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/middleware.rb:10:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-failures-0.4.5/lib/sidekiq/failures/middleware.rb:9:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by mhenrixon** [comment]
Give me a few minutes and I'll have that fixed. You are upgrading from 3.x right?

**Comment by kapso** [comment]
Yes

**Comment by mhenrixon** [comment]
Does the console or output have something like `unique: true is no longer valid. Please set it to the type of lock required like: "unique: :until_executed"`

**Comment by kapso** [comment]
Not sure, this is on prod, so detailed logs are switched off.

**Comment by mhenrixon** [comment]
This should be a warning

**Comment by kapso** [comment]
Searched papertrail/logs, found nothing.

**Comment by mhenrixon** [comment]
Thanks that helps a lot

**Comment by mhenrixon** [comment]
How is your configuration? Could you post your `SidekiqUniqueJobs.configure do |config|`?

**Comment by mhenrixon** [comment]
Or the output of `SidekiqUniqueJobs.default_lock` would help

**Comment by mhenrixon** [comment]
Try v4.0.13

**Comment by kapso** [comment]
@mhenrixon looks like 4.0.13 has been pulled out, dont see it here https://rubygems.org/gems/sidekiq-unique-jobs

**Comment by mhenrixon** [comment]
Ah sorry I bumped and tagged it but forgot to release. Done now!
