### ISSUE TITLE
SidekiqUniqueJobs::ScriptError: release_lock.lua NOSCRIPT No matching script.

### ISSUE THREAD

**Issue by heaven** [mhenrixon/sidekiq-unique-jobs#187]
Got this on heroku while trying to switch to jruby.

File	/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/scripts.rb:32

Here's the full backtrace:
```
release_lock.lua NOSCRIPT No matching script. Please use EVAL. local unique_key = KEYS[1] local job_id = ARGV[1] local stored_jid = redis.pcall('get', unique_key) if stored_jid then if stored_jid == job_id or stored_jid == '2' then redis.pcall('del', unique_key) redis.pcall('hdel', 'uniquejobs', job_id) return 1 else return 0 end else return -1 end 
/app/vendor/bundle/jruby/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:121:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.31
/lib/new_relic/agent/instrumentation/redis.rb:42:in `block in call'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/datastores.rb:111:in `block in wrap'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/datastores.rb:108:in `wrap'
/app/vendor/bundle/jruby/2.2.0/gems/newrelic_rpm-3.14.1.31
/lib/new_relic/agent/instrumentation/redis.rb:41:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:2394:in `block in _eval'
/app/vendor/bundle/jruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:58:in `block in synchronize'
/app/vendor/ruby-2.2.3-jruby-9.0.5.0/lib/ruby/stdlib/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/jruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:58:in `synchronize'
/app/vendor/bundle/jruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:2393:in `_eval'
/app/vendor/bundle/jruby/2.2.0/gems/redis-3.3.0/lib/redis.rb:2445:in `evalsha'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/scripts.rb:28:in `block in call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq-unique-jobs.rb:68:in `block in connection'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq.rb:92:in `block in redis'
/app/vendor/bundle/jruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block in with'
org/jruby/RubyThread.java:660:in `handle_interrupt'
/app/vendor/bundle/jruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
org/jruby/RubyThread.java:660:in `handle_interrupt'
/app/vendor/bundle/jruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq.rb:89:in `redis'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq-unique-jobs.rb:68:in `connection'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/scripts.rb:26:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/unlockable.rb:10:in `unlock_by_key'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_executed.rb:31:in `unlock'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_executed.rb:23:in `execute'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/logging.rb:32:in `with_context'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke' org/jruby/RubyProc.java:318:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:129:in `block in process'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:168:in `stats'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:128:in `process'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:81:in `process_one'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in `run'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'
/app/vendor/bundle/jruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by mhenrixon** [comment]
This has been mentioned before, not much I can do if I remember correctly. We try to reload the script file when this occurs. I recommend you try what is in master if the problem persists.
