### ISSUE TITLE
Can't delete Sidekiq::Job after 5.0.1

### ISSUE THREAD

**Issue by moyashipan** [mhenrixon/sidekiq-unique-jobs#218]
related to #215

My app is using sidekiq-unique-job and normal sidekiq-job (e.g. not contains `sidekiq_options unique: ...`).

After sidekiq-unique-jobs 5.0.1.
I tried to delete a normal job in SidekiqWeb, but following error shown:
```
SidekiqUniqueJobs::UniqueKeyMissing (unique_key is required)
```
Why does sidekiq-unique-jobs require that normal sidekiq-job have unique_key?
Should I set unique options to __ALL__ sidekiq-jobs?
https://github.com/mhenrixon/sidekiq-unique-jobs#usage-with-activejob

my config:
- sidekiq (4.2.10)
- sidekiq-unique-jobs (5.0.1)

**Comment by mhenrixon** [comment]
Sounds like a bug to me. Do you have the full stacktrace?

**Comment by moyashipan** [comment]
```
vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.1/lib/sidekiq_unique_jobs/scripts/release_lock.rb:14:in `initialize'
vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.1/lib/sidekiq_unique_jobs/scripts/release_lock.rb:8:in `new'
vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.1/lib/sidekiq_unique_jobs/scripts/release_lock.rb:8:in `execute'
vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.1/lib/sidekiq_unique_jobs/unlockable.rb:10:in `unlock_by_key'
vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.1/lib/sidekiq_unique_jobs/unlockable.rb:6:in `unlock'
vendor/bundle/ruby/2.3.0/gems/sidekiq-unique-jobs-5.0.1/lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb:95:in `delete_ext'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web/application.rb:86:in `block in <class:WebApplication>'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web/application.rb:266:in `instance_exec'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web/application.rb:266:in `block in call'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web/application.rb:262:in `catch'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web/application.rb:262:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web.rb:103:in `call'
vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/web.rb:108:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `each'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:725:in `call'
vendor/bundle/ruby/2.3.0/gems/xray-rails-0.2.0/lib/xray/middleware.rb:38:in `call'
vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
vendor/bundle/ruby/2.3.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
vendor/bundle/ruby/2.3.0/gems/bullet-5.5.1/lib/bullet/rack.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/meta_request-0.4.0/lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
vendor/bundle/ruby/2.3.0/gems/meta_request-0.4.0/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
vendor/bundle/ruby/2.3.0/gems/http_accept_language-2.1.0/lib/http_accept_language/middleware.rb:14:in `call'
vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:553:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-contrib-1.2.0/lib/rack/contrib/response_headers.rb:17:in `call'
vendor/bundle/ruby/2.3.0/gems/meta_request-0.4.0/lib/meta_request/middlewares/headers.rb:16:in `call'
vendor/bundle/ruby/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundle/ruby/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:26:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:81:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:81:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-mini-profiler-0.10.2/lib/mini_profiler/profiler.rb:282:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by moyashipan** [comment]
👍

**Comment by miltzi** [comment]
Thanks for this :) Had the same issue
