### ISSUE TITLE
bundle exec jobs console does not work

### ISSUE THREAD

**Issue by USvER** [mhenrixon/sidekiq-unique-jobs#253]
```
Use `keys '*', 1000 to display the first 1000 unique keys matching '*'
Use `del '*', 1000, true (default) to see how many keys would be deleted for the pattern '*'
Use `del '*', 1000, false to delete the first 1000 keys matching '*'
bundler: failed to load command: jobs (/root/.rbenv/versions/2.4.1/bin/jobs)
Errno::ENOENT: No such file or directory @ rb_sysopen - console
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/magic-file.rb:8:in `initialize'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/magic-file.rb:8:in `open'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/magic-file.rb:8:in `open'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/input-method.rb:101:in `initialize'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/context.rb:86:in `new'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/context.rb:86:in `initialize'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:412:in `new'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:412:in `initialize'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:381:in `new'
  /root/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:381:in `start'
  /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/cli.rb:44:in `console'
  /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sidekiq-unique-jobs-5.0.10/bin/jobs:7:in `<top (required)>'
  /root/.rbenv/versions/2.4.1/bin/jobs:22:in `load'
  /root/.rbenv/versions/2.4.1/bin/jobs:22:in `<top (required)>'
```

**Comment by kholbekj** [comment]
You installed it with bundler? 
What's the output of `bundle show sidekiq-unique-jobs`?

**Comment by USvER** [comment]
# bundle show sidekiq-unique-jobs
/root/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sidekiq-unique-jobs-5.0.10


17 ноября 2017, 12:07:10, от Kasper Holbek Jensen &lt;notifications@github.com&gt;:

**Comment by beniusij** [comment]
I am experiencing the same issue.
![screen shot 2018-03-15 at 16 17 37](https://user-images.githubusercontent.com/15200194/37476916-42338a8e-286e-11e8-8a8a-045565fc7a38.png)
