### ISSUE TITLE
:until_executed is throwing errors and not requeuing the job.

### ISSUE THREAD

**Issue by martyphee** [mhenrixon/sidekiq-unique-jobs#256]
I'm seeing a number of errors like this where the job isn't getting requeued after the following error.

Error Message
**Problem compiling release_lock. Invalid LUA**

Dependancies
```
sidekiq (4.2.10)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-ent (1.5.1)
      algorithms
      sidekiq (~> 4, >= 4.2.4)
      sidekiq-pro (~> 3, >= 3.4.0)
    sidekiq-pro (3.5.3)
      sidekiq (>= 4.1.5)
    sidekiq-scheduler (2.1.2)
      hashie (~> 3.4)
      redis (~> 3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
    sidekiq-unique-jobs (5.0.10)
      sidekiq (>= 4.0, <= 6.0)
      thor (~> 0)
```

Worker Configuration
```
sidekiq_options queue:  :within5minutes,
                    unique: :until_executed,
                    retry:  10
```

Stacktrace
```
17270 TID-gpq0r14h4 WARN: {"context":"Job raised exception","job":{"class":"SettlementWorker","args":
[75400712],"retry":10,"queue":"within5minutes","unique_expiration":7200,"backtrace":true,"unique":"until_executed","jid":"8b59fbb8570a3ce42708f109","created_at":1519043964.616448,"unique_prefix":"uniquejobs","unique_args":
[75400712],"unique_digest":"uniquejobs:0169f01b963755da7963f022d374560f","enqueued_at":1519043964.6170187,"error_message":"Problem compiling release_lock. Invalid LUA syntax?",
"error_class":"SidekiqUniqueJobs::ScriptError","failed_at":1519043965.1175787,
"retry_count":0,
"error_backtrace":["/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/scripts.rb:45:in 
`handle_error'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/scripts.rb:30:in `rescue in 
call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/scripts.rb:28:in `call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/scripts/release_lock.rb:25:in `execute'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/scripts/release_lock.rb:10:in 
`execute'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/unlockable.rb:13:in 
`unlock_by_key'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/lock/until_executed.rb:37:in 
`unlock'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/lock/until_executed.rb:25:in `ensure in execute'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/lock/until_executed.rb:28:in 
`execute'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:18:in 
`call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-pro-3.5.3/lib/sidekiq/batch/middleware.rb:33:in `call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in 
invoke'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-ent-1.5.1/lib/sidekiq-ent/limiter/middleware.rb:38:in `call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in 
invoke'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in 
`call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in 
`call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in 
process'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `call'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'","/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'"]},"jobstr":"{\"class\":\"Payments::PayPalSettlementWorker\",\"args\":[75400712],\"retry\":10,\"queue\":\"within5minutes\",\"unique_expiration\":7200,\"backtrace\":true,\"unique\":\"until_executed\",\"jid\":\"8b59fbb8570a3ce42708f109\",\"created_at\":1519043964.616448,\"unique_prefix\":\"uniquejobs\",\"unique_args\":[75400712],\"unique_digest\":\"uniquejobs:0169f01b963755da7963f022d374560f\",\"enqueued_at\":1519043964.6170187}"} ```

**Comment by mhenrixon** [comment]
@martyphee which version of redis are you on? Redis like the server, not the gem

**Comment by MaicolBen** [comment]
@mhenrixon It happened to me as well, the server version is 4.0.10 which is the lastest currently.

**Comment by mhenrixon** [comment]
@MaicolBen would it be at all possible for you to upgrade to `v6.0.0.rc7`? It does require ruby > 2.3. If you can I would strongly recommend an upgrade.

**Comment by MaicolBen** [comment]
@mhenrixon what are the major differences? `unique` got renamed to `lock`, I'm asking because I have tons of jobs using `unique`

**Comment by MaicolBen** [comment]
The error in version 5 isn't exactly the same, it throws `Problem compiling acquire_loc`, in the version 6 now it throws `Problem compiling create. Message: ERR unknown command 'script'` with `unique` and `lock`. It didn't work the first time, so I don't think I have to the delete jobs manually.

**Comment by MaicolBen** [comment]
If you don't know what is the problem about, can I achieve the same behavior of `until_executed` with another one and a hack?

**Comment by mhenrixon** [comment]
To me it looks like there is something off with your Redis installation somehow. Admittedly I have only tested on redis 4.0.10 but I've never seen any of the above errors. I'd need more details to help like what OS you are on? How did you install redis? What version of the redis gem? what version of the sidekiq gem?

**Comment by MaicolBen** [comment]
sidekiq: 5.0.5
redis gem: 4.0.0
Mac OS High Sierra 10.13.6
redis server: 4.0.10 (installed with brew)

Remember that this only happens on the specs (test environment)

**Comment by mhenrixon** [comment]
I know this sounds silly but would you mind uninstalling and then installing the redis server again? I just want to make absolutely sure that it isn't a borked installation. 

How do you configure the REDIS_URL that sidekiq uses? Are you using different urls for testing and development?

**Comment by MaicolBen** [comment]
It's happening in Circle CI (ubuntu) as well. The url was configured as follows:
```ruby
config.redis = { url: 'redis://localhost:6888', namespace: :sidekiq }
```

I have the following configured in the rails helper:
```
Sidekiq.configure_client do |config|
      config.redis = ConnectionPool.new(size: 5) { Redis.new }
    end
```

And I have the `rspec-sidekiq` installed

What could differ between `while_executing` and `until_executed` in testing?

**Comment by mhenrixon** [comment]
Ah! Did you see the section about testing in the README for v6? I recommend you do 

```ruby
RSpec.configure do |config|
  config.before do 
    SidekiqUniqueJobs.config.enabled = false
  end 
end
```

You do not want to be testing uniqueness really.

**Comment by MaicolBen** [comment]
yeah but I didn't know it wasn't in the 5 version, after adding that in v6 fixed the issue, thanks!
