### ISSUE TITLE
concurrent-ruby 1.1.1 is causing this gem to break

### ISSUE THREAD

**Issue by kapso** [mhenrixon/sidekiq-unique-jobs#340]
```
identifier Config needs to be constant (NameError)
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/synchronization/abstract_struct.rb:140:in `define_struct_class'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/mutable_struct.rb:213:in `block in define_struct'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/mutable_struct.rb:212:in `define_struct'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.1/lib/concurrent/mutable_struct.rb:207:in `new'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs.rb:45:in `<module:SidekiqUniqueJobs>'
	from /Users/kapil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sidekiq-unique-jobs-6.0.6/lib/sidekiq_unique_jobs.rb:40:in `<main>'
```

**Comment by Slike9** [comment]
@kapso Seems your project uses https://github.com/railsconfig/config gem which defines `Config` constant in global space. The pr https://github.com/ruby-concurrency/concurrent-ruby/pull/776 fixes the problem.
