### ISSUE TITLE
until_and_while_executing with sidekiq pro `reliable_scheduler!`

### ISSUE THREAD

**Issue by piton4eg** [mhenrixon/sidekiq-unique-jobs#411]
**Describe the bug**
The jobs doesn't really retry after failing when sidekiq pro option "reliable_scheduler!" is enabled, it silently starts and finishes without executing code.

**Expected behavior**
The job is retrying

**Current behavior**
The job runs and finishes

**Worker class**
```ruby
class HardWorker
  include Sidekiq::Worker

  sidekiq_options unique: :until_and_while_executing

  def perform
    sleep 2

    p "Hello, world!"
    raise "BOOM!"
  end
end
```

**Additional context**
Gemfile:
```
gem 'sidekiq-pro', '3.7.1'

# doesn't work with 6.0.13
gem 'sidekiq-unique-jobs', '6.0.13'
# works well with 4.0.17
# gem 'sidekiq-unique-jobs', '~> 4.0.17'
```

Sidekiq initializer:
```
Sidekiq.configure_server do |config|
  config.reliable_scheduler!
end
```

I've created repository with sample here: https://github.com/piton4eg/sidekiq-unique-jobs

**Comment by serg-kovalev** [comment]
@piton4eg 💯 thanks for reporting this and for app sample
@mhenrixon have you had a chance to look at it?

**Comment by mhenrixon** [comment]
@serg-kovalev it's been pretty crazy lately. I'm trying to get to a place where I can get some help from @piton4eg to debug this (I do not own a license of sidekiq-pro myself).

I am pretty sure it has to do with the reliable scheduler somehow but we need to find some time together to have a look. I'm sure it's something pretty simple though.

**Comment by piton4eg** [comment]
@mhenrixon let me know how I can help you to debug this. I've created the test repository to show the issue

**Comment by joscal-nl** [comment]
@mhenrixon Is there any progress or status update for this report?

**Comment by serg-kovalev** [comment]
It still fails on `6.0.15`
```
2019-11-20T15:32:58.700Z 43336 TID-1jw INFO: Sidekiq Pro 3.7.1, commercially licensed.  Thanks for your support!
2019-11-20T15:32:58.701Z 43336 TID-1jw INFO: Booting Sidekiq 4.2.10 with redis options {:url=>nil}
2019-11-20T15:32:58.725Z 43336 TID-1jw INFO: Starting processing, hit Ctrl-C to stop
2019-11-20T15:33:09.426Z 43336 TID-1k6 HardWorker JID-dfcd4d321541f716c04994f6 INFO: start
"Hello, world!"
2019-11-20T15:33:11.482Z 43336 TID-1k6 HardWorker JID-dfcd4d321541f716c04994f6 INFO: fail: 2.056 sec
2019-11-20T15:33:11.485Z 43336 TID-1k6 WARN: {"context":"Job raised exception","job":{"class":"HardWorker","args":[],"retry":true,"queue":"default","unique":"until_and_while_executing","jid":"dfcd4d321541f716c04994f6","created_at":1574263989.3990638,"lock_timeout":0,"lock_expiration":null,"unique_prefix":"uniquejobs","unique_args":[],"unique_digest":"uniquejobs:0966e3da8504afbb5fc401b413cb1b7d:RUN","enqueued_at":1574263989.4035861,"error_message":"BOOM!","error_class":"RuntimeError","failed_at":1574263991.483549,"retry_count":0},"jobstr":"{\"class\":\"HardWorker\",\"args\":[],\"retry\":true,\"queue\":\"default\",\"unique\":\"until_and_while_executing\",\"jid\":\"dfcd4d321541f716c04994f6\",\"created_at\":1574263989.3990638,\"lock_timeout\":0,\"lock_expiration\":null,\"unique_prefix\":\"uniquejobs\",\"unique_args\":[],\"unique_digest\":\"uniquejobs:0966e3da8504afbb5fc401b413cb1b7d\",\"enqueued_at\":1574263989.4035861}"}
2019-11-20T15:33:11.486Z 43336 TID-1k6 WARN: RuntimeError: BOOM!
2019-11-20T15:33:11.486Z 43336 TID-1k6 WARN: /Users/sergey/development/groupon/sidekiq-unique-jobs/app/workers/hard_worker.rb:10:in `perform'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block in process'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in Sidekiq'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block in process'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/server/middleware.rb:34:in `block in call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:22:in `block in execute'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/lock/while_executing.rb:38:in `execute'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:22:in `execute'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/server/middleware.rb:33:in `block in call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:43:in `block in with_context'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:43:in `with_context'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-unique-jobs-6.0.15/lib/sidekiq_unique_jobs/server/middleware.rb:32:in `call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-pro-3.7.1/lib/sidekiq/batch/middleware.rb:54:in `call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block in process'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block in process'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in Sidekiq'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/Users/sergey/.rvm/gems/jruby-9.1.17.0@sidekiq-unique-jobs/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'
^C2019-11-20T15:33:17.245Z 43336 TID-1jw INFO: Shutting down
```

**Comment by mhenrixon** [comment]
@serg-kovalev @joscal-nl I'm looking into it right now

**Comment by mhenrixon** [comment]
Another fix for until and while executing has been released. See #447 for the diff (new version v6.0.16). I will have to test this particular scenario as well (haven't done that yet) but it should be more reliable now even if this particular issue wasn't fixed.

**Comment by mhenrixon** [comment]
Version to test right now is `v6.0.18` if anyone could give it a try @serg-kovalev @joscal-nl @piton4eg

**Comment by joscal-nl** [comment]
@mhenrixon We tested it with out own application.
It works! Thank you for your effort.

`2019-12-03T08:47:44.682Z 82040 TID-owasvmh3s WARN: RuntimeError: BOOM!
2019-12-03T08:48:54.479Z 82040 TID-owasvb7hg StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 INFO: start
2019-12-03T08:48:54.485Z 82040 TID-owasvb7hg StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 SidekiqUniqueJobs::Server::Middleware DIG-uniquejobs:8363c4b419e1fb0753f757e9fecfb2db ERROR: Failed to execute job, restoring lock
2019-12-03T08:48:54.489Z 82040 TID-owasvb7hg StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 INFO: fail: 0.01 sec
2019-12-03T08:48:54.490Z 82040 TID-owasvb7hg WARN: RuntimeError: BOOM!
2019-12-03T08:50:39.801Z 82040 TID-owaru0hbg StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 INFO: start
2019-12-03T08:50:39.804Z 82040 TID-owaru0hbg StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 SidekiqUniqueJobs::Server::Middleware DIG-uniquejobs:8363c4b419e1fb0753f757e9fecfb2db ERROR: Failed to execute job, restoring lock
2019-12-03T08:50:39.806Z 82040 TID-owaru0hbg StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 INFO: fail: 0.005 sec
2019-12-03T08:50:44.103Z 82040 TID-owat0kf4k WARN: RuntimeError: BOOM!
2019-12-03T08:50:48.503Z 82040 TID-owasvfqrc StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 INFO: start
2019-12-03T08:50:48.506Z 82040 TID-owasvfqrc StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 SidekiqUniqueJobs::Server::Middleware DIG-uniquejobs:8363c4b419e1fb0753f757e9fecfb2db ERROR: Failed to execute job, restoring lock
2019-12-03T08:50:48.508Z 82040 TID-owasvfqrc StockItemWorkers::ValidatingStockItemWorker JID-9bd0e7c07d295a389ee20349 INFO: fail: 0.005 sec
2019-12-03T08:50:48.509Z 82040 TID-owasvfqrc WARN: RuntimeError: BOOM!`

**Comment by serg-kovalev** [comment]
@mhenrixon thank you!
I just checked, the fix works! Well done!
