### ISSUE TITLE
Missing web interface

### ISSUE THREAD

**Issue by sylvainbx** [mhenrixon/sidekiq-unique-jobs#514]
**Describe the bug**
According to the README file, we can setup a web interface using
```
require 'sidekiq_unique_jobs/web'
mount Sidekiq::Web, at: '/sidekiq'
```

**Expected behavior**
The web interface should be accessible 

**Current behavior**
When starting my rails app, the following error message is shown and the process terminates immediately:
```
17:38:32 web.1    | /home/sylvain/.rvm/gems/ruby-2.6.5@fab-manager/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- sidekiq_unique_jobs/web (LoadError)
17:38:32 web.1    |     from /home/sylvain/.rvm/gems/ruby-2.6.5@fab-manager/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
...
```

**Additional context**
I've made a research for any file named web in the gem directory but I couldn't find anything:
```bash
find /home/sylvain/.rvm/gems/ruby-2.6.5@fab-manager/gems/sidekiq-unique-jobs-5.0.2/ -name "*web*"
# no results
```

**Comment by sylvainbx** [comment]
Ok, I've found myself the issue: for an unknown reason bundler has installed v5.0.2 by default, and the web ui is only available from v6
