### ISSUE TITLE
Error "undefined method `redis_info' for Sidekiq:Module" on upgrade 

### ISSUE THREAD

**Issue by kriom** [mhenrixon/sidekiq-unique-jobs#740]
**Describe the bug**
I try to upgrade the gems sidekiq-unique-jobs to 7.1.27 and  sidekiq 7.01 using this [configuration ](https://github.com/mhenrixon/sidekiq-unique-jobs#add-the-middleware)

**Expected behavior**
sidekiq start

**Current behavior**
sidekiq fail to start with this erroer message
```
2022-11-16T11:50:37.769Z pid=70837 tid=2qj5 WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup","_config":"#<Sidekiq::Config:0x000055ec6cb75008>"}
2022-11-16T11:50:37.771Z pid=70837 tid=2qj5 WARN: NoMethodError: undefined method `redis_info' for Sidekiq:Module
Did you mean?  redis_pool
2022-11-16T11:50:37.771Z pid=70837 tid=2qj5 WARN: /home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:201:in `fetch_redis_version'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/config.rb:314:in `redis_version'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:123:in `redis_version'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:62:in `do_call'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:48:in `block in call_script'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:156:in `block in redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:153:in `redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq.rb:73:in `redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/connection.rb:19:in `redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:47:in `call_script'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/update_version.rb:18:in `call'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/server.rb:35:in `start'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/server.rb:20:in `block in configure'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/component.rb:58:in `block in fire_event'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/component.rb:57:in `each'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/component.rb:57:in `fire_event'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/cli.rb:105:in `run'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/bin/sidekiq:31:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.7.6/bin/sidekiq:23:in `load'
/home/me/.rvm/gems/ruby-2.7.6/bin/sidekiq:23:in `<main>'
/home/me/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
/home/me/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'
undefined method `redis_info' for Sidekiq:Module
Did you mean?  redis_pool
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:201:in `fetch_redis_version'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/config.rb:314:in `redis_version'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:123:in `redis_version'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:62:in `do_call'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:48:in `block in call_script'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:156:in `block in redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/home/me/.rvm/gems/ruby-2.7.6/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:153:in `redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq.rb:73:in `redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/connection.rb:19:in `redis'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:47:in `call_script'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/update_version.rb:18:in `call'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/server.rb:35:in `start'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/server.rb:20:in `block in configure'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/component.rb:58:in `block in fire_event'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/component.rb:57:in `each'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/component.rb:57:in `fire_event'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/lib/sidekiq/cli.rb:105:in `run'
/home/me/.rvm/gems/ruby-2.7.6/gems/sidekiq-7.0.1/bin/sidekiq:31:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.7.6/bin/sidekiq:23:in `load'
/home/me/.rvm/gems/ruby-2.7.6/bin/sidekiq:23:in `<main>'
/home/me/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
/home/me/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by strika** [comment]
Maybe this https://github.com/mhenrixon/sidekiq-unique-jobs/issues/736#issuecomment-1279937963 is useful for you. It seems that sidekiq-unique-jobs is not compatible with Sidekiq 7.

**Comment by kriom** [comment]
Thank you, at the moment, I will limit my upgrade to sidekiq (6.5.8)
